source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?('/')
  "https://github.com/#{repo_name}.git"
end

gem 'rails', '~> 5.1.4'
gem 'sqlite3'

group :test do
  gem 'murker', github: 'aderyabin/murker', branch: 'master'
  gem 'pry-byebug'
  gem 'rspec-rails', '~> 3.7'
end
