# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 014aa71f77d6d62039c334783355fb5d4ee769e23b9c99fa7c04c07e09d4e145792e9393bb1282879dda5165b740074295885c519bc12f1bcaf9539c96763adc

test:
  secret_key_base: 0d8c2383f87e6c5285c31e28eecaa8ab81ed40a4dbbe3ead0d2cf29e79a7138130979b12cb42084ae4a61c2bcee41370d31dd92ec472775cc6fa491acc8d745a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
