sudo: false
language: ruby
rvm:
  - 2.3.2
before_install:
  - gem install bundler -v 1.16.1
script:
  - RAILS_ENV=test bundle exec rake spec
  - bundle exec appraisal install && RAILS_ENV=test bundle exec appraisal rails-5 cucumber
cache: bundler
