sudo: false
language: ruby
rvm:
  - 2.3.2
gemfile:
  - gemfiles/rails_5.gemfile
before_install:
  - gem install bundler -v 1.16.0
script:
  - RAILS_ENV=test rspec
  - RAILS_ENV=test bundle exec appraisal rails-5 cucumber
