sudo: false
language: ruby
rvm:
  - 2.3.2
gemfile:
  - gemfiles/rails_5.gemfile
before_install:
  - gem install bundler -v 1.16.1
script:
  - RAILS_ENV=test bunele exec rake spec
  - RAILS_ENV=test bundle exec appraisal rails-5 cucumber
cache: bundler
