---
openapi: 3.0.0
paths:
  "/martians/{id}":
    get:
      responses:
        "'200'":
          content:
            application/json:
              schema:
                type: object
                required:
                - name
                - age
                - ololo
                - thisIsGonnaFailToo
                properties:
                  name:
                    type: string
                  age:
                    type: integer
                  ololo:
                    type: string