---
openapi: 3.0.0
paths:
  "/v1/martians":
    get:
      responses:
        "'200'":
          content:
            application/json:
              schema:
                type: array
                minItems: 1
                uniqueItems: true
                items:
                  type: object
                  required:
                  - name
                  - age
                  - ololo
                  properties:
                    name:
                      type: string
                    age:
                      type: integer
                    ololo:
                      type: string