require 'json-schema-generator'

module Murker
  # Generates OpenAPI v3 schema for Interaction
  # Output is Ruby object representing schema, it may be serialized to yml|json
  class Generator
    OPEN_API_VERSION = '3.0.0'.freeze
    OPEN_API_INFO = {
      'title' => 'Generated by Murker',
      'version' => Murker::VERSION.to_s
    }.freeze
    JSON_SCHEMA_VERSION = 'draft4'.freeze
    JSON_SCHEMA_UNWANTED_FIELDS = %w[$schema description].freeze
    APPLICATION_JSON_CONTENT_TYPE = 'application/json'.freeze

    attr_reader :interaction

    def initialize(interaction:)
      @interaction = interaction
    end

    def self.call(interaction)
      new(interaction).call
    end

    def call
      {
        'openapi' => OPEN_API_VERSION,
        'info' => OPEN_API_INFO,
        'paths' => {
          handle_path_params(interaction.endpoint_path) => {
            interaction.verb.downcase => response_schema
          }
        }
      }
    end

    private

    def handle_path_params(path)
      path.gsub(/:(\w*)/) { |_s| "{#{$1}}" }
    end

    def response_schema
      status = interaction.status
      verb = interaction.verb
      endpoint_path = interaction.endpoint_path
      {
        'responses' => {
          "'#{status}'" => {
            'description' => "#{verb} #{endpoint_path} -> #{status}",
            'content' => {
              APPLICATION_JSON_CONTENT_TYPE => { 'schema' => body_schema }
            }
          }
        }
      }
    end

    def body_schema
      serialized_schema = JSON::SchemaGenerator.generate(
        '', # description
        JSON.dump(interaction.body),
        schema_version: 'draft4'
      )
      schema_object = JSON.parse(serialized_schema)
      remove_unexpected_fields(schema_object)
    end

    def remove_unexpected_fields(schema_object)
      schema_object.tap do |schema|
        JSON_SCHEMA_UNWANTED_FIELDS.each { |field| schema.delete field }
      end
    end
  end
end
