require 'murker/path_params_generator'
require 'murker/query_params_generator'
require 'murker/utils'

module Murker
  # Generates OpenAPI v3 schema for Interaction
  # Output is Ruby object representing schema, it may be serialized to yml|json
  class Generator
    include Murker::Utils

    OPEN_API_VERSION = '3.0.0'.freeze
    OPEN_API_INFO = {
      'title' => 'Generated by Murker',
      'version' => Murker::VERSION.to_s,
    }.freeze
    JSON_SCHEMA_VERSION = 'draft4'.freeze
    APPLICATION_JSON_CONTENT_TYPE = 'application/json'.freeze

    attr_reader :interaction

    extend Forwardable
    delegate %i[
      verb
      endpoint_path
      path_info
      path_params
      query_params
      payload
      body
      status
    ] => :interaction

    def initialize(interaction:)
      @interaction = interaction
    end

    def self.call(interaction)
      new(interaction).call
    end

    def call
      {
        'openapi' => OPEN_API_VERSION,
        'info' => OPEN_API_INFO,
        'paths' => {
          change_path_params_from_colon_to_curly_braces(endpoint_path) => {
            verb.downcase => verb_schema,
          },
        },
      }
    end

    private

    def verb_schema
      params_schema = parameters_schema
      if params_schema
        {
          'parameters' => params_schema,
          'responses' => response_schema,
        }
      else
        { 'responses' => response_schema }
      end
    end

    def change_path_params_from_colon_to_curly_braces(path)
      path.gsub(/:(\w*)/) { |_s| "{#{Regexp.last_match(1)}}" }
    end

    def parameters_schema
      schema = (Array(path_params_schema) + Array(query_params_schema)).compact
      schema.empty? ? nil : schema
    end

    def path_params_schema
      PathParamsGenerator.call(path_params)
    end

    def query_params_schema
      QueryParamsGenerator.call(query_params)
    end

    def response_schema
      {
        "'#{status}'" => {
          'description' => "#{verb} #{endpoint_path} -> #{status}",
          'content' => {
            APPLICATION_JSON_CONTENT_TYPE => {
              'schema' => schema_by_object(body),
            },
          },
        },
      }
    end
  end
end
